version: '3.9'  # Версия docker-compose

services:
  web:  # Имя сервиса
    build: .  # Сборка образа из текущей директории (где находится Dockerfile)
    container_name: python_server  # Имя контейнера
    ports:
      - "5000:5000"  # Проброс порта хост:контейнер
    volumes:
      - .:/server  # Привязка текущей директории на хосте к директории /server в контейнере
    environment:
      - ENV=production  # Пример переменной окружения
    restart: always  # Политика перезапуска
